### ISSUE TITLE
Intermediate results output

### ISSUE THREAD

**Issue by TimSkvortsov** [pylelab/USalign#1]
Hi,  I was wondering if an option to save intermediate results could be added. For example, having the distance matrix from the all-against-all pairwise structure alignments (the one in Supplementary Figure 13 (a) of the US-align paper biorXiv preprint) would be very useful.

In addition, would it be possible to add a little bit more information about different `--outfmt` options?

Thank you!

**Comment by kad-ecoli** [comment]
I have just added option ``-full T`` for all-against-all pairwise alignment result in multiple structure alignment. You can use it as follow:
```bash
USalign -dir chains/ list -suffix .pdb -mm 4 -full T
```

**Comment by TimSkvortsov** [comment]
Many thanks, that's perfect! I have a quick question about MSTA: each pairwise alignment generates two TM-scores, what TM-score is used for the construction of the pairwise distance matrix for MSTA?

**Comment by kad-ecoli** [comment]
The one normalized by the shorter structure.

**Comment by TimSkvortsov** [comment]
> The one normalized by the shorter structure.

Thanks!
