### ISSUE TITLE
Alternative interface -- tm/usalign from pdb text or from a struct?

### ISSUE THREAD

**Issue by danpf** [pylelab/USalign#10]
This is kind of a big ask, but it would be nice if I didn't have to write temporary files when I'm getting transformation matrices between two structures. an example would be if my pdbs/cifs are in a database, and another example would be during a pymol session ( https://github.com/Pymol-Scripts/Pymol-script-repo/blob/master/tmalign.py#L70 i know many people use this currently)

Ideally some sort of workflow like: 
```
Mol mobile_mol1 = mol_from_pdb_text(pdb_text1);
Mol const immobile_mol2 = mol_from_pdb_text(pdb_text2);
Matrix transformation_matrix = TMalign_main(mobile_mol1, immobile_mol2, Lnorm_ass, d0_scale, i_opt, a_opt, u_opt, d_opt, force_fast_opt, TMcut);
std::string aligned_mol_text(pdb_text_from_mol(mobile_mol1);
```
quick access to things like the transformation matrix and the aligned molecule (either as a reference or a copy(preferably options for both) ) would be very nice and integreate nicely with existing c++ workflows and python scripts (if python bindings were added)

edit: I just wanted to say, i realize that this library doesn't really use structs / classes and is more function based ( which is fine, this was just an example ) but something similar could be written in the functional way as well.

**Comment by kad-ecoli** [comment]
You do not have to write a temporary file to get the transformation matrix. The flag `` -m - `` will print the matrix to stdout. By the way, we are working on a new pymol plugin at https://raw.githubusercontent.com/pylelab/USalign/master/usalign.py
which performs essentially the same function as the legacy TMalign pymol plugin you quoted.

**Comment by danpf** [comment]
Hi @kad-ecoli 
I think I was not clear  sorry! :/ -- I want a function to run USalign from pdb/cif std::string, or some struct.

I do not want to write my molecule to disk in cif/pdb format when running tmalign.

something somewhat like what the steinegger lab did here:
https://github.com/steineggerlab/foldseek/blob/42fed613978ca47e4a52acb7b7119a466d2a7d1f/src/strucclustutils/tmalign.cpp#L104
they get their molecule data from a database as a string, and then process it into the inputs for tmalign, and then run tmalign but don't actually write the molecule to a file first.

**Comment by kad-ecoli** [comment]
Just to be clear. The [python binding you cite](https://github.com/Pymol-Scripts/Pymol-script-repo/blob/master/tmalign.py#L70) indeed writes molecule to disk in cif/pdb format (see line 115-116)
```python
    save(mobile_filename, mobile_ca_sele)
    save(target_filename, target_ca_sele)
```

It seems you want a C++ API which perform the following two things
[1] Parse the content (not file name) of the pdb/mmcif file in std::string into some struct
[2] Perform TMalign/USalign on the struct from [1].

While this is not impossible, it would involve a lot of refactoring. So I wonder the actual user case to see whether it is worthwhile. May I know why you would want such an API?

**Comment by danpf** [comment]
Hi,

Yes, sorry that might have led to some confusion.  That was just an example, along with the 'structures in a database as strings' example of times when it would be useful to not have to write to the filesystem.  Perhaps that was not the best example though, as it is not a high throughput scenario.

One example would be similar to this paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8504633/
you may want to change a protein's properties (like maybe it's pI is too high/low) by making chimeras, so you would go into a full structure database, usalign on a region to all proteins and then filter based on ones that match your specifications.  Often times things like this require lots and lots of structural alignment and require breaking reference structures into domains to make sure all regions are appropriately 'sampled'.

My reasoning is that when doing massive amounts of structural alignments (millions, or more, domain to protein, protein to domains, etc) you pay the cost of writing, reading, and deleting the pdbs, and then the algorithm becomes a smaller part of the overall runtime as disk r/w capacity is filled (happens a lot unfortunately).  If everything is in a database, or already in memory, you don't have to pay that cost for every 'job' and things are faster and don't waste computational resources.

I know it would involve a lot of refactoring and would likely take a lot of work - so I don't expect it to be done, but I just wanted to raise the issue so that you were aware that it is a problem people have run into if you weren't already.

**Comment by kad-ecoli** [comment]
US-align can read data from stdin. Supposed you have 10 pdb files named PDB0.pdb PDB1.pdb ... PDB9.pdb in the database, each correctly ends with the line "END" and/or "ENDMDL", as well as a single query file, US-align can perform a one-against-all alignment by:
```bash
cat  PDB0.pdb PDB1.pdb PDB2.pdb PDB3.pdb PDB4.pdb PDB5.pdb PDB6.pdb PDB7.pdb PDB8.pdb PDB9.pdb| USalign -ter 0 query.pdb - 
```
Here, the  "-" instructs US-align to read from stdin.

For your particular usage case, you can combine all pdb files (including domains and segments) into a big string, where different pdbs are separated by "END". You can then supply this string to US-align in the command line (e.g., through python's subprocess module) through stdin. This is less elegant than the API you mention, but it does not require any refactoring.
