### ISSUE TITLE
How to install and set up US align

### ISSUE THREAD

**Issue by yang-nei** [pylelab/USalign#15]
I wanna use US align on my local computers,  including macOS or linux , but I have little experience on computer comand line and programs. Is there a more detail way about install commands which can tell me ?

**Comment by huiwenke** [comment]
For single structure pair alignment you can use US-align online webserver (https://zhanggroup.org/US-align/) instead. If you need to perform large-scale structure searching, you can invite a linux administrator to deploy a MineProt (https://github.com/huiwenke/MineProt) application for you, which includes a graphical interface of US-align.

**Comment by yang-nei** [comment]
Thank for your response! I 've token a look in MineProt github. but I 'm cruious whether US align on MineProt can use database  from myself hit another my database? another question is, what are the necessary on my hardward of my computers (CUP, GUP, RAM ,SSD)

**Comment by huiwenke** [comment]
MineProt supports 1-to-N alignment currently, and it picks out results with TM-score > 0.5.
4G 2 cores (no need for GPU) are enough to deploy MineProt, while storage space depends on the size of your database.

**Comment by kad-ecoli** [comment]
Thanks @huiwenke for the MineProt front end.

For the question from @yang-nei , if you have no previous experience in installing program on MacOS or Linux, you can download the pre-compiled binaries executables at the bottom of https://zhanggroup.org/US-align/ . You only need to unzip USalignLinux64.zip or USalignMac.zip on your local computer and they can be run in command line.

We are working on a US-align plugin to be used within PyMOL and it should be ready in a few months.
