### ISSUE TITLE
-fast option with multimer alignment

### ISSUE THREAD

**Issue by mrauha** [pylelab/USalign#16]
Hi,

In Supplementary Figure 9, it is demonstrated that fTM-align significantly speeds up the alignment of larger structures. However, using the `-fast` flag for multimer alignment has no effect on the calculation time or the alignment results. Below is the code to replicate this, I'm using the current version of US-align from this repository.

```bash
wget https://files.rcsb.org/download/7NYH.cif
wget https://files.rcsb.org/download/7NYU.cif
time ./USalign 7NYU.cif 7NYH.cif -mm 1 -ter 0 -fast | head -16 | tail -3
time ./USalign 7NYU.cif 7NYH.cif -mm 1 -ter 0 | head -16 | tail -3
```
gives 
```
# fTM-align
Aligned length= 2195, RMSD=   0.83, Seq_ID=n_identical/n_aligned= 1.000
TM-score= 0.47471 (normalized by length of Structure_1: L=4615, d0=18.82)
TM-score= 0.99666 (normalized by length of Structure_2: L=2195, d0=14.28)

real	0m12.052s

# TM-align
Aligned length= 2195, RMSD=   0.83, Seq_ID=n_identical/n_aligned= 1.000
TM-score= 0.47471 (normalized by length of Structure_1: L=4615, d0=18.82)
TM-score= 0.99666 (normalized by length of Structure_2: L=2195, d0=14.28)

real	0m12.052s
```

Is there a reason why fTM-align doesn't work for multimers?

Thanks!

**Comment by kad-ecoli** [comment]
-fast is always turned on for -mm 1 if the length of the smaller complex is greater than 500 residues. This is implemented by line 645 of https://github.com/pylelab/USalign/blob/master/USalign.cpp
