### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by yoavatsmonraz** [pylelab/USalign#17]
Dear Sir/Madam, thank for making this code available, its truly an excellent tool for structural biology. However, I'd like to suggest a modification to the code that would allow instead of a single atom to define a residue, would instead allow a few ASL like language as is implemented in NAMD/AMBER/MDtraj which would allow greater flexibility in the application of the code.
All the best, Y

**Comment by kad-ecoli** [comment]
Dear user,
Your suggestion is not that easily implementable. The TM-score is only calibrated for using one single atom per residue. Using more atoms will require a re-calibration of the d0 factor, which is not trivial.
