### ISSUE TITLE
How to use the -i and -I tags

### ISSUE THREAD

**Issue by sadiogo** [pylelab/USalign#19]
Hi! Can you give examples on how to use the -i and -I tags?

Does it work with the -mm 4 option?

Do I need to specify the path to align.txt file? Or will using just "-i" search for an align.txt file in the current directory?

When -i is used, what does the program actually do with this information ((how does an "initial alignment" contribute to the algorithm)?

Similarly, what does the program do when -I is used (does it perform a structural alignment based on the sequence alignment)?

**Comment by kad-ecoli** [comment]
-i and -I are for -mm 0. not -mm 4.
You need the specify the path to align.txt. You can place align.txt at the current folder. In such as case, you can use a command similar to the following:
```bash
USalign structure1.pdb structure2.pdb -I align.txt
```

When -i is used, US-align will use the specified alignment (together with the five other built-in alignments) as initial alignments, starting from which iterative superimposition-alignment is performed.

When -I is used, US-align performs a structural superimposition based on the provided sequence alignment.
