### ISSUE TITLE
Pymol superimposed pdb issue 

### ISSUE THREAD

**Issue by Cventura18** [pylelab/USalign#22]
Hello,

I am having some issues when trying to use the Pymol-generated files from USalign. When I try to open the pdb file it only shows me structure 1 and has an issue showing structure 2. The png file shows both structures and how they are super imposed. This is the error message that shows up in Pymol when opening the figures  'Selector-Error: Invalid selection name "structure2".
polymer and ( ( structure1 and c. A ) or ( structure2 and c. A ) )<--'

**Comment by kad-ecoli** [comment]
Can you make a screen shot of the current pymol session. It seems you did not have a file with name "structure2" opened by pymol.

**Comment by kad-ecoli** [comment]
Close ticket as there is no follow up from the user.
