### ISSUE TITLE
Multi Chain alignement ?

### ISSUE THREAD

**Issue by Anarcyst** [pylelab/USalign#23]
Does US-align support the alignment of a monomer to a multi-chain protein complex while considering the spatial relationship between the chains in the complex? For example, I have a monomer that I'm trying to align to an antibody fragment composed of two chains. Could you provide any examples or documentation on how to conduct such alignments using US-align

**Comment by kad-ecoli** [comment]
The recommended flag for your purpose is 
```bash
USalign -mm 1 monomer.pdb complex.pdb -ter 0
```
This will align the monomer to the most similar chain in the complex.
