### ISSUE TITLE
US-align is a sequence-independent structural alignment tool or not?

### ISSUE THREAD

**Issue by Wenjian-Ma** [pylelab/USalign#26]
Hi! authors, 
I would like to perform the structural alignment between a pair of proteins in the context of only considering backbone atom coordinates (i.e., protein sequence is unavailable). But I'm not sure that US-align is a sequence-independent tool or not due to that US-align is defined as a tool for sequence-order dependent rigid structural alignments in the paper and `-TMscore 0` means the sequence independent structure alignment in [https://zhanggroup.org/US-align/help/.](https://zhanggroup.org/US-align/help/) Could you kindly help address my concerns? Thanks!

**Comment by kad-ecoli** [comment]
US-align is sequence independent, i.e., it ignores the amino acid/nucleotide residue types when matching the residue coordinates.  The alignment process ignores side chain atoms.

Sequence-dependent and sequence-order dependent is completely different.
Sequence-order dependent means that when residue i1 and j1 in structure 1 align to residues i2 and j2 in structure 2, if i1<j1, it is always true that i2<j2. This is unrelated to amino acid/nucleotide type.
