### ISSUE TITLE
Additional Output for CP and sequence order (semi-)independent alignments

### ISSUE THREAD

**Issue by rbdavid** [pylelab/USalign#3]
Is it possible to have an additional file written that maps the aligned residue indices between structures that have been aligned using sequence independent methods? Or, is the linear representation of the sequence alignment output by the code sufficient to figure this mapping out?

**Comment by rbdavid** [comment]
I hadn't run the -mm 5 and -mm 6 option. So, this question only stands for the CP implementation.

**Comment by kad-ecoli** [comment]
For -mm 5 and -mm 6, we indeed output the aligned residue indices as you mentioned.
For CP, linear representation of the sequence alignment should be enough the figure out the mapping because there is at most one permutation site (marked by ``*``).

**Comment by rbdavid** [comment]
Is there documentation, whether in USalign or TMalign software packages or elsewhere, on the CP mapping? I'm trying to write code around the TMalign/USalign output for the CP method to get the mapping but have not been able to find any description of the formatting.

**Comment by kad-ecoli** [comment]
I have just pushed a commit at https://github.com/pylelab/USalign/commit/524eec6e7fb02c74bd2d40b7721f9a6dd2196ed9 to print out the residue correspondence in CP alignment. Could you check if it is what you want?

**Comment by rbdavid** [comment]
Yeah, that's exactly what I was thinking. Thanks so much! 

I'm gonna briefly get on my soapbox for a moment. Any structural alignment code should, at least, report the translational and rotational matrices needed to recreate the alignment or the atomic/residue mapping that was used to align the structures. Both is preferred. With the former, I can recreate the alignment on the fly rather than rerunning the alignment or using the `-o` parameter to save the aligned structure to storage. With the latter, I can immediately write code to visualize/analyze the aligned regions looking for a variety of different features. Alright, phew, glad I got that off my chest.

Thanks for compiling these alignment codes into one package. This is exactly what I need for my work!

**Comment by kad-ecoli** [comment]
For translational and rotational matrices, use ``-m`` option. Thank you for using our program.
