### ISSUE TITLE
Use USalign to protein pocket

### ISSUE THREAD

**Issue by liyue9129** [pylelab/USalign#31]
Hi !
I want to use USalign to calculate the similarity between two protein pockets, but I found that USalign only aligns the A chains of the two pockets. Then I tried using -split 0, but it also failed. So, what should I do to use USalign to calculate the similarity between the two protein pockets?
![image](https://github.com/user-attachments/assets/13f46105-7e3e-4bfc-9bcc-c1fe81027409)

Thank you！

**Comment by kad-ecoli** [comment]
USalign by default only aligns the first chain. If you need to align two or more chains, use ``-ter 1`` or ``-ter 0``. If one pocket contains two or more chains, you may want to use ``-mm 1``.

**Comment by liyue9129** [comment]
Thank you so much for your help!
