### ISSUE TITLE
PDB alignment is not correct 

### ISSUE THREAD

**Issue by mukulem** [pylelab/USalign#4]
Hi, I am trying to align two protein structure, one the PDB has the format below as shown in figure below
<img width="458" alt="image" src="https://user-images.githubusercontent.com/105665325/200154043-b528730d-7552-4183-becf-7b81a1ef17a8.png">

Can USalign able read E2552 correctly, coz in alignment it seems it is unable to read that portion.

**Comment by kad-ecoli** [comment]
Yes, USalign (or any common alignment program I use) should read E2552 just fine. May I know why do you feel the residue was not read correctly? You can attach the PDB file as a zip archive and we can further check,

**Comment by mukulem** [comment]
[PDB files.zip](https://github.com/pylelab/USalign/files/9946169/PDB.files.zip)
Here are the PDB files, 
Both are same similar structure they should align in theory, But i am not really sure why they are not aligning. I initially thought it could be due to E2552.

Thanks looking forward for your response

**Comment by kad-ecoli** [comment]
The PDB structures are complexes with multiple chains, By default, US-align performs monomer structure alignment for the first chain only. If you want to perform oligomer structure alignment, you will need to use ``-mm 1 -ter 1``, for example.

**Comment by mukulem** [comment]
Thank you so much
Yeah I did the same, but the one is predicted and the other is true structure 
still it looks like one half is completely opposite to other when aligned

**Comment by kad-ecoli** [comment]
The two complex structures are NOT similar. It is true that at individual chain level, PDB1 (green) and PDB2 (cyan) are similar. However, if you consider the assembled complex structure, chain A/B in PDB1, which corresponds to chain E/D in PDB2, are located at opposite site of the complex. This means the predicted structure does not assemble the complex correctly even though the structure of each chain is more or less correct.
![mm1](https://user-images.githubusercontent.com/7478069/200616808-d34a9bed-e2ba-4234-97c6-52db90526de9.png)
