### ISSUE TITLE
All-to-all alignments & transformation matrices

### ISSUE THREAD

**Issue by mrauha** [pylelab/USalign#6]
I'm running quite large all-vs-all comparisons, and would need the transformation matrices. When I use -m with the -dir option, I get the message "-m or -o cannot be set with -dir, -dir1 or -dir2". Bruteforcing this with for-loops of course works, but slows things up I think.

Is there any way to trick them out or could one be added, eg to one file similarly with consensus alignments with the -mm 4 option. Would be useful :)

**Comment by kad-ecoli** [comment]
I have just pushed a commit. It is still not possible to write the transformation matrix to file when used with -dir. However, using ``-m -``, US-align can print the transformation matric to screen even when using -dir option.

**Comment by mrauha** [comment]
Excellent, thank you a lot!
