### ISSUE TITLE
US-align stuck at a chain

### ISSUE THREAD

**Issue by chanqian18** [pylelab/USalign#7]
With large .mmcif files, the program seems to get stuck at a chain number, even after letting it run for up to 30 mins. All other results took seconds to produce.
![image](https://user-images.githubusercontent.com/67110786/206223679-d5b856fd-b328-4739-8dcd-90b8b7e29372.png)

**Comment by kad-ecoli** [comment]
I am not able to reproduce this error. It took my version of US-align less than 1 min to complete the computation. The command  I use is
```bash
USalign af_Q93309_195_560.pdb 7n6g.cif -outfmt 2 -ter 0 -split 2
```
The PDB and mmCIF files are attached with this post.
[issue7.zip](https://github.com/pylelab/USalign/files/10179002/issue7.zip)
